-- Migration for existing mall_chat schema

ALTER TABLE post
  ADD COLUMN category_id BIGINT NOT NULL DEFAULT 1 COMMENT '分类ID' AFTER user_id,
  ADD COLUMN audit_status TINYINT NOT NULL DEFAULT 1 COMMENT '审核状态：0待审，1通过，2拒绝' AFTER status,
  ADD COLUMN audit_reason VARCHAR(255) DEFAULT NULL COMMENT '审核原因' AFTER audit_status,
  ADD COLUMN audit_updated_at DATETIME DEFAULT NULL COMMENT '审核时间' AFTER audit_reason,
  ADD INDEX idx_post_category_id (category_id);

ALTER TABLE comment
  ADD COLUMN audit_status TINYINT NOT NULL DEFAULT 1 COMMENT '审核状态：0待审，1通过，2拒绝' AFTER status,
  ADD COLUMN audit_reason VARCHAR(255) DEFAULT NULL COMMENT '审核原因' AFTER audit_status,
  ADD COLUMN audit_updated_at DATETIME DEFAULT NULL COMMENT '审核时间' AFTER audit_reason;

CREATE TABLE IF NOT EXISTS category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分类ID',
  name VARCHAR(64) NOT NULL COMMENT '分类名称',
  parent_id BIGINT DEFAULT NULL COMMENT '父级ID',
  level TINYINT NOT NULL DEFAULT 1 COMMENT '层级',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常，0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_category_parent_id (parent_id),
  INDEX idx_category_level (level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='帖子分类';

INSERT IGNORE INTO category (id, name, parent_id, level, sort, status)
VALUES (1, '默认', NULL, 1, 0, 1);

CREATE TABLE IF NOT EXISTS tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '标签ID',
  name VARCHAR(64) NOT NULL UNIQUE COMMENT '标签名称',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1正常，0禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标签';

CREATE TABLE IF NOT EXISTS post_tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '关联ID',
  post_id BIGINT NOT NULL COMMENT '帖子ID',
  tag_id BIGINT NOT NULL COMMENT '标签ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_post_tag (post_id, tag_id),
  INDEX idx_post_tag_post_id (post_id),
  INDEX idx_post_tag_tag_id (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='帖子-标签关联';

CREATE TABLE IF NOT EXISTS sign_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '签到记录ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  sign_date DATE NOT NULL COMMENT '签到日期',
  sign_time DATETIME NOT NULL COMMENT '签到时间',
  is_retro TINYINT NOT NULL DEFAULT 0 COMMENT '是否补签：0否，1是',
  reward_status TINYINT NOT NULL DEFAULT 0 COMMENT '奖励发放状态：0未发放，1已发放',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_sign_user_date (user_id, sign_date),
  INDEX idx_sign_user_id (user_id),
  INDEX idx_sign_date (sign_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='签到记录';

CREATE TABLE IF NOT EXISTS sensitive_word (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '敏感词ID',
  word VARCHAR(64) NOT NULL COMMENT '敏感词',
  level TINYINT NOT NULL DEFAULT 1 COMMENT '等级：1低，2中，3高',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是，0否',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_sensitive_word (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词库';

CREATE TABLE IF NOT EXISTS sensitive_whitelist (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '白名单ID',
  word VARCHAR(64) NOT NULL COMMENT '白名单词',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是，0否',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_sensitive_whitelist (word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词白名单';

CREATE TABLE IF NOT EXISTS content_audit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '审核记录ID',
  biz_type VARCHAR(16) NOT NULL COMMENT '业务类型：post/comment',
  biz_id BIGINT NOT NULL COMMENT '业务ID',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0待审，1通过，2拒绝',
  hit_level TINYINT NOT NULL DEFAULT 0 COMMENT '命中等级：0无，1低，2中，3高',
  hit_words VARCHAR(512) DEFAULT NULL COMMENT '命中词列表(逗号分隔)',
  operator_id BIGINT DEFAULT NULL COMMENT '审核人ID',
  reason VARCHAR(255) DEFAULT NULL COMMENT '审核原因',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_audit_biz (biz_type, biz_id),
  INDEX idx_audit_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容审核记录';
